#!/usr/bin/env bash
# script that transfers a file from our client to a server
a=$#
if [ $a -lt 3 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
else
   scp -i $4 $1 $3@$2:~/
fi
