#!/usr/bin/env bash
# installs nginx on the web-01 server
sudo apt update
sudo apt install nginx -y
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
