#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create custom 404 HTML page
sudo bash -c "cat <<EOF > /usr/share/nginx/html/404.html
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF"

# Configure custom 404 page
sudo sed -i '/^\tlocation \/ {$/a \\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}\n' /etc/nginx/sites-available/default

# Test configuration file and reload Nginx
sudo nginx -t && sudo service nginx restart
