#!/usr/bin/env bash
# nstall and configure HAproxy on your lb-01 server.

sudo apt install software-properties-common -y
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt update -y
sudo apt install haproxy -y
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo -e "frontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend apache_webservers\n\nbackend apache_webservers\n\tbalance roundrobin\n\tserver 145696-web-01\t100.26.235.207:80 check\n\tserver 145696-web-02\t54.86.208.71:80 check\n"  >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
