#!/usr/bin/env bash
#Creating a script that uses if, else if and else statements
i=0
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
    esac
    ((i++))
done
